import numpy as n
print("*** NUMPY MODULE ***")
arr1=n.array([[20,40],[22,33]])
arr2=n.array([[11,44],[55,22]])
print("Addition of arr1 & arr2 is : \n",arr1+arr2)
print("Subtraction of arr1 & arr2 is : \n",arr1-arr2)
print("Multiplication of arr1 & arr2 is : \n",arr1*arr2)
print("Division of arr1 & arr2 is : \n",arr1/arr2)
print("Power of arr1 to arr2 is : \n",n.power(arr1,arr2))
print("Minimum of arr1 is : \n",n.amin(arr1))
print("Maximum of arr1 is : \n",n.amax(arr1))
print("Mean of arr1 is : \n",n.mean(arr1))
print("Median of arr1 is : \n",n.median(arr1))
print("Columnwise minimum of arr1 is : \n",n.amin(arr1,axis=0))
print("Rowwise minimum of arr1 is : \n",n.amin(arr1,axis=1))
