a=eval(input("ENTER VALUE OF A"))
b=eval(input("ENTER VALUE OF B"))
c=eval(input("ENTER VALUE OF C"))
d=eval(input("ENTER VALUE OF D"))
e=eval(input("ENTER VALUE OF E"))
code=input("ENTER EXPRESSION ")
result=eval(code)
print("The value of a={0},b={1},c={2},d={3},e={4}".format(a,b,c,d,e))
print("EXPN IS :",code)
print("RESULT IS :",result)
