name=input("NAME : ")
regno=input("REGISTER NAME : ")
branch=input("BRANCH : ")
sem=int(input("SEM :"))
phno=int(input("PHNO :"))
dob=input("DOB : ")
age=int(input("AGE : "))
email=input("EMAIL :")
gender=input("GENDER ")
addr=input("ADDRESS ")
print("STUDENT NAME :",name)
print("REGISTER NO :",regno)
print("STUDENT BRANCH IS :",branch)
print("STUDENT SEM :",sem)
print("STUDENT PHONE NO :",phno)
print("DOB :",dob)
print("STUDENT AGE :",age)
print("ADDRESS : ",addr)
